name: Pokedexer
options:
  bundleIdPrefix: des.c5inco
  deploymentTarget:
    iOS: "16.0"
  xcodeVersion: "15.0"
  groupSortPosition: top

packages:
  KMPNativeCoroutines:
    url: https://github.com/rickclephas/KMP-NativeCoroutines
    exactVersion: 1.0.0-ALPHA-40

settings:
  base:
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic

targets:
  Pokedexer:
    type: application
    platform: iOS
    sources:
      - path: iosApp
        excludes:
          - "*.xcconfig"
    dependencies:
      - package: KMPNativeCoroutines
        product: KMPNativeCoroutinesAsync
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: des.c5inco.pokedexer
        INFOPLIST_FILE: iosApp/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        LD_RUNPATH_SEARCH_PATHS: $(inherited) @executable_path/Frameworks
        FRAMEWORK_SEARCH_PATHS:
          - $(inherited)
          - $(SRCROOT)/../shared/build/bin/iosSimulatorArm64/debugFramework
          - $(SRCROOT)/../shared/build/bin/iosArm64/releaseFramework
        OTHER_LDFLAGS:
          - $(inherited)
          - -framework Shared
      configs:
        Debug:
          FRAMEWORK_SEARCH_PATHS:
            - $(inherited)
            - $(SRCROOT)/../shared/build/bin/iosSimulatorArm64/debugFramework
        Release:
          FRAMEWORK_SEARCH_PATHS:
            - $(inherited)
            - $(SRCROOT)/../shared/build/bin/iosArm64/releaseFramework
    preBuildScripts:
      - name: Build Shared Framework
        script: |
          cd "$SRCROOT/.."
          if [ "$CONFIGURATION" = "Debug" ]; then
            ./gradlew :shared:linkDebugFrameworkIosSimulatorArm64 --no-daemon
          else
            ./gradlew :shared:linkReleaseFrameworkIosArm64 --no-daemon
          fi
        basedOnDependencyAnalysis: false

schemes:
  Pokedexer:
    build:
      targets:
        Pokedexer: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

